(maint) Check suitability in Facter::Util::Resolution.value
Consider the following irb session

irb(main):001:0> require 'facter'
=> true
irb(main):002:0> Facter.fact(:netmask)
LoadError: cannot load such file -- win32ole

What?  This happens because irb is inspecting the object for
display, hence calling to_s on the array of fact resolutions,
hence calling value on each resolution, and down in
Facter::Util::Resolution.value there is no check for suitability
so it happily executes the setcode block for all platforms.
And boom.

So this patch adds a suitability check in value as a safety net
of sorts.